
language: node_js
node_js:
 - "node"
before_install:
- npm install -g jspm
- npm install -g yarn
- yarn  
- jspm install
cache:
 directories:
  - node_modules
sudo: true
script:
- jspm bundle lib/main --inject
